# Build GenAI_Code/ — minimal submission-ready code folder at repo root.
# Run from anywhere:  .\scripts\build-genai-code-folder.ps1
# Then: add your PDF report + verify prompts.txt; zip as  ROLLNO NAME.ZIP  per instructor.

$ErrorActionPreference = "Stop"
$Root = Split-Path -Parent $PSScriptRoot
$Dest = Join-Path $Root "GenAI_Code"

Write-Host "Output: $Dest" -ForegroundColor Cyan

if (Test-Path $Dest) {
    Remove-Item -Recurse -Force $Dest
}
New-Item -ItemType Directory -Path $Dest | Out-Null
New-Item -ItemType Directory -Path (Join-Path $Dest "scripts") | Out-Null

function Invoke-Robocopy {
    param([string]$SrcRel, [string]$DstRel, [string[]]$ExclDirs = @(), [string[]]$ExclFiles = @())
    $src = Join-Path $Root $SrcRel
    $dst = Join-Path $Dest $DstRel
    if (-not (Test-Path $src)) { return }
    New-Item -ItemType Directory -Path $dst -Force | Out-Null
    $args = [System.Collections.ArrayList]@($src, $dst, "/E", "/NFL", "/NDL", "/NJH", "/NJS", "/NC", "/NS")
    if ($ExclDirs.Count -gt 0) {
        [void]$args.Add("/XD")
        foreach ($d in $ExclDirs) { [void]$args.Add($d) }
    }
    if ($ExclFiles.Count -gt 0) {
        [void]$args.Add("/XF")
        foreach ($f in $ExclFiles) { [void]$args.Add($f) }
    }
    & robocopy $args | Out-Null
    if ($LASTEXITCODE -ge 8) {
        throw "robocopy failed ($LASTEXITCODE): $SrcRel -> $DstRel"
    }
}

# Backend (no venv, caches, local DB, secrets)
Invoke-Robocopy "backend" "backend" @(
    ".venv", ".venv311", "__pycache__", "chroma_data", "uploads", ".pytest_cache", "logs"
) @(".env", ".coverage", "*.db")

# Restore uploads/.gitkeep if empty dir
$up = Join-Path $Dest "backend\uploads"
if (-not (Test-Path $up)) { New-Item -ItemType Directory -Path $up | Out-Null }
$gk = Join-Path $Root "backend\uploads\.gitkeep"
if (Test-Path $gk) { Copy-Item $gk (Join-Path $Dest "backend\uploads\.gitkeep") -Force }

# Frontend (no node_modules / build output)
Invoke-Robocopy "frontend" "frontend" @("node_modules", "dist", ".vite") @(".env.local")

# Experiments + data
Invoke-Robocopy "experiments" "experiments" @(".ipynb_checkpoints") @()
if (Test-Path (Join-Path $Root "data")) {
    Invoke-Robocopy "data" "data" @() @()
}

# Docs: LaTeX source + figures (exclude large zip if present)
Invoke-Robocopy "docs" "docs" @() @("*.zip")

# Helper scripts for Docker / submission
Copy-Item (Join-Path $Root "scripts\docker-start.ps1") (Join-Path $Dest "scripts\") -Force
Copy-Item (Join-Path $Root "scripts\docker-fresh.ps1") (Join-Path $Dest "scripts\") -Force
Copy-Item (Join-Path $PSScriptRoot "build-genai-code-folder.ps1") (Join-Path $Dest "scripts\build-genai-code-folder.ps1") -Force

# Root artifacts
foreach ($f in @(
    "prompts.txt",
    "docker-compose.yml",
    "README.md",
    ".gitignore"
)) {
    $p = Join-Path $Root $f
    if (Test-Path $p) { Copy-Item $p (Join-Path $Dest $f) -Force }
}

# CI reference (optional but shows reproducibility)
if (Test-Path (Join-Path $Root ".github\workflows\ci.yml")) {
    New-Item -ItemType Directory -Path (Join-Path $Dest ".github\workflows") -Force | Out-Null
    Copy-Item (Join-Path $Root ".github\workflows\ci.yml") (Join-Path $Dest ".github\workflows\") -Force
}

$readmeTxt = @"
GradeUp AI — submission code bundle (GenAI_Code)
================================================

This folder was generated by: scripts\\build-genai-code-folder.ps1

Before zipping for the course:
1. Add your research paper as a PDF (LNCS), if not submitted separately.
2. Ensure prompts.txt includes all prompts required by the instructor (app + any GPT assistance).
3. Do NOT include backend\\.env with real secrets — graders use backend\\.env.example.
4. Name the final ZIP exactly as required (e.g. ROLLNO NAME.ZIP).

Local quick run:
  cd backend
  copy .env.example .env   (then edit)
  pip install -r requirements.txt
  python -m uvicorn main:app --host 127.0.0.1 --port 8000

Docker from THIS folder:
  docker compose up -d
  (needs backend/.env next to this tree — copy from .env.example)

Regenerate this folder from the full repo after code changes:
  .\\scripts\\build-genai-code-folder.ps1
"@
Set-Content -Path (Join-Path $Dest "SUBMISSION_README.txt") -Value $readmeTxt -Encoding UTF8

Write-Host "Done. Next: add PDF, review prompts.txt, zip GenAI_Code as ROLLNO NAME.ZIP" -ForegroundColor Green
exit 0
